[package]
name = "aspecky/luauevent"
version = "1.2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
author = "Aspecky"
description = "A faster and more equipped Luau implementation of BindableEvent"

exclude = ["**"]
include = ["default.project.json", "src", "src/**", "LICENSE", "wally.toml"]

[dependencies]
